export const LABEL_TICKETS = 'Tickets'
export const PATH_TICKETS = '/tickets'
export const LABEL_TRACKER = 'Monitoramento'
export const PATH_TRACKER = '/tracker'
export const LABEL_SETTINGS = 'Configurações'
export const PATH_SETTINGS = '/settings'